language: node_js
node_js: '0.10'

script:
  - MIWG_PATH=tmp/bpmn-miwg-test-suite grunt

before_install:
  - mkdir -p tmp
  - git clone https://github.com/bpmn-io/bpmn-miwg-test-suite.git tmp/bpmn-miwg-test-suite
  - npm install -g grunt-cli wiredeps
  - wiredeps --branch=$TRAVIS_BRANCH --tag=$TRAVIS_TAG --verbose